const style = {
  /////////////////////////////////////////////

  itemHeader: {
    height: "41px",
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    alignItems: "center" as "center",
  },

  itemHeaderTable: {
    fontSize: "17px",
    fontWeight: "700",
  },

  headerStatus: {
    fontSize: "13px",
    width: "79.68px",
    height: "23.02px",
    borderRadius: "15px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center" as "center",
    fontWeight: "700",
    marginTop: "-10px",
  },

  actionContainer: {
    height: "48px",
    borderTop: "1px solid #484848",
    marginTop: "44px",
    display: "flex",

    justifyContent: "end",
    alignItems: "center",
  },

  actionButton: {
    width: "171px",
    height: "36px",
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    fontSize: "14px",
    fontWeight: "700",
    alignItems: "center",
    borderRadius: "10px",
    padding: "0 15px",

    marginTop: "12px",
  },

  btnArrow: {
    marginTop: "15px",
  },
  rawItemContainer: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "10px",
    marginTop: "10px",
  },
  itemHeaderDate: {
    fontSize: "12px",
    fontWeight: "400",
    marginTop: "-10px",
  },

  orderItemContainer: {
    height: "100%",
    display: "flex" as "flex",
    flexDirection: "column" as "column",
    justifyContent: "space-between",
    borderRadius: "16px",
    gap: "1rem",
  },
  orderBottomSection: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "10px",
  },
  tableHeaderText: {
    fontSize: "12px",
    fontWeight: 400,
    margin: 0,
    lineHeight: "14.52px",
  },
  tableText: {
    fontSize: "12px",
    fontWeight: 400,
    margin: "0px 0px 6px 0px",
    lineHeight: "14.52px",
  },

  tableHandwaveHeaderText: {
    fontSize: "12px",
    fontWeight: 300,
    marginBottom: -5,
    marginTop: 5,
  },
  closeBtn: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 16px 0 20px",
    height: "36px",
    maxWidth: "177px",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: 700,
    outline: "none",
  },
  closeBtnContainer: {
    display: "flex",
    justifyContent: "flex-end",
    width: "100%",
  },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    marginTop: "-6px",
    marginBottom: "10px",
  },
  totalRowText: {
    fontSize: "14px",
    fontWeight: 700,
  },
  horizontalLine: {
    height: "1px",
    width: "100%",
  },
  expandButton: {
    position: "absolute" as "absolute",
    fontSize: 12,
    fontWeight: 600,
    padding: "5px 10px 2px 10px",
    cursor: "pointer",
    borderRadius: "30px",
    width: "127px",
    height: "28px",
    justifyContent: "center",
    alignItems: "center",
  },

  tableExpandButton: {
    position: "absolute" as "absolute",
    fontSize: 12,
    fontWeight: 600,
    display: "flex",
    cursor: "pointer",
    borderRadius: "30px",
    width: "127px",
    height: "28px",
    justifyContent: "center",
    alignItems: "center",
  },

  ///////////////////////
  container: {
    borderRadius: "15px",
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
    padding: "23px 13px 11px 13px",
    height: "100%",
    width: "100%",
  },

  bottomContainer: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
    padding: "0px 13px 11px 13px",
    height: "100%",
    width: "100%",
  },

  handwaveItemHeader: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    width: "100%",
    gap: "1rem",
    alignItems: "center",
  },
  orderItemHeaderRest: {
    textAlign: "left" as "left",
    fontWeight: "600",
    lineHeight: "14.52px",
    marginTop: "11px",
    marginLeft: "22px",
  },
  orderItemHeaderActiveRest: {
    textAlign: "right" as "right",
    fontSize: "16px",
    fontWeight: "700",
    lineHeight: "14.52px",
    marginTop: "0px",
  },
  handwaveItemNo: {
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "700",
    borderRadius: "15px",
    cursor: "pointer",
  },
  textTwoRowStatus: {
    fontWeight: "bold",
    textAlign: "center" as "center",
    height: "fit-content",
    padding: "0.3rem 0.5rem",
    borderRadius: 12,
  },
  middleRow: {
    fontWeight: "400",
    borderRadius: "10px",
    justifyContent: "center",
    padding: "12.56px 12.87px 0px 12.21px",
  },
  disabledText: {
    fontSize: 12,
    fontWeight: 400,

    marginTop: 0,
  },
  arrowIcon: {
    position: "relative" as "relative",
    left: 6,
    fontSize: "20px",
    marginRight: 5,
  },
  middleRowContent: {
    display: "flex",
    flexDirection: "column" as "column",
  },
  orderItemName: {
    color: "#000",
    fontSize: "16px",
    fontWeight: "700",
  },
  orderNo: {
    color: "#464646",
    fontSize: "12px",
    fontWeight: "400",
    flex: "none",
  },
  handwaveStatus: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "15px",
    minWidth: "73px",
  },
  orderDate: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "16.94px",
  },
  orderTime: {
    fontSize: "14px",
    fontWeight: "700",
    lineHeight: "16.94px",
  },
  hrLine: {
    height: "1px",
    width: "100%",
    backgroundColor: "rgba(215, 215, 215, 1)",
  },
  orderTable: {
    height: "100%",
    width: "100%",
    borderSpacing: "0px 10px",
  },
  orderTableHeadingsRow: {
    color: "#737373",
    fontSize: "12px",
    fontWeight: "400",
    marginBottom: "0.5rem",
  },
  editBox: {
    width: "max-content",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "center" as "center",
    borderRadius: "15px",
    position: "absolute" as "absolute",
    marginLeft: 45,
    padding: "0.5rem",
    gap: "0.4rem",
    zIndex: "100",
  },
  editItems: {
    alignItems: "center",
    padding: "0px 10px 0 10px",
    cursor: "pointer",
    display: "inline-block",
  },
  cancelOrder: {
    display: "flex",
    alignItems: "center",
    padding: "10px 10px 0px 10px",
    cursor: "pointer",
  },

  orderTableRow: {
    color: "#1A1A1A",
    fontSize: "12px",
    fontWeight: "500",
    marginTop: "0.5rem",
    marginBottom: "0.5rem",
  },
  orderTableHeading: {
    textAlign: "start",
    fontWeight: "400",
  },
  orderBottomSectionTable: {
    display: "flex",
    justifyContent: "center",
    marginTop: "4px",
    padding: "0.4rem 0.2rem",
  },
  viewmoreText: {
    display: "flex",
    justifyContent: "flex-start",
    width: "fit-content",
    cursor: "pointer",
  },
  orderItemBody: {
    display: "flex",
    flexDirection: "row" as "row",
    gap: "1rem",
  },
  orderTotalText: {
    fontSize: "12px",
    fontWeight: "700",
  },
  orderSeeDetailsBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    background: "#E4EFFF",
    outline: "none",
    color: "#2F2F2F",
    fontSize: "12px",
    fontWeight: "400",
    width: "6.125rem",
  },
  orderPayBillsBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    background: "#000",
    color: "#FFF",
    fontSize: "12px",
    fontWeight: "700",
  },
  settingTexts: {
    margin: 0,
    marginTop: "0.7rem",
    marginBottom: "auto",
    fontSize: "14px",
    fontWeight: "600",
    display: "inline",
    lineHeight: "16.94px",
  },

  settingIcons: {
    marginRight: 6,
    fontSize: "14px",
    width: "10.31px",
    height: "13.1px ",
    display: "inline",
    fontWeight: "600",
  },
};
export default style;
