const style = {
  headerBtn: {
    padding: "8px",
    borderRadius: "12px",
    textAlign: "center" as "center",
    fontWeight: 500,
    cursor: "pointer",
    position: "relative" as "relative",
  },
  headerBtnNew: {
    padding: "8px 8px",
    borderRadius: "12px",
    textAlign: "center" as "center",
    fontWeight: 500,
    cursor: "pointer",
    position: "relative" as "relative",
  },
  menuManagementHeader: {
    padding: "1rem 1rem",
    marginBottom: 0,
  },
  menuHeaderLeftStatus: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "fit-content",
    height: 50,
    padding: "0.5rem 1rem",
    borderRadius: "15px",
  },
  settingsContainer: {
    display: "flex",
    flexDirection: "row" as "row",
    alignItems: "center" as "center",
    padding: "6px",
    marginTop: 3,
    borderRadius: "12px",
    fontWeight: 500,
    cursor: "pointer",
  },
  // searchBar: {
  //   width: "190%",
  //   height: 35,
  //   marginRight: "auto",
  //   marginLeft: "auto",
  //   borderRadius: "10px",
  // },
  searchBar: {
    width: "fit-content",
    height: 35,
    marginRight: "auto",
    marginLeft: "auto",
    borderRadius: "10px",
  },
  menuSearchBar: {
    width: 380,
    margin: "0 0.5rem",
    borderRadius: "10px",
  },
  orderItemContainer: {
    borderRadius: "15px",
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
    padding: "15px",
  },
  orderItemNo: {
    fontSize: "1.125rem",
    minWidth: "3.938rem",
    height: "3.938rem",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "400",
    borderRadius: "15px",
  },
  orderItemHeader: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    width: "100%",
    gap: "1rem",
    alignItems: "center",
  },
  text: {
    width: 30,
    height: 20,
  },
  orderStatus: {
    width: "fit-content",
    height: 30,
    borderRadius: "15px",
    gap: "3rem",
  },
  menuLeft: {
    marginTop: 10,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "fit-content",
    height: 50,
    padding: "0.5rem",
    borderRadius: "15px",
  },
};
export default style;
