const style = {
  tableContainer: {
    padding: "1rem",
    height: "74vh",
    overflowY: "scroll",
  },
  settingIcon: {
    display: "flex",
    justifyContent: "center" as "center",
    alignItems: "center",
    fontSize: 20,
    cursor: "pointer",
    height: 33,
    borderRadius: "10px",
  },
  container: {
    borderRadius: "10px",
    padding: 1,
    minWidth: "152px",
    minHeight: "150px",
    aspectRatio: "1 / 1",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "space-between",
    cursor: "pointer",
  },
  AddTableContainer: {
    marginTop: "1rem",
    borderRadius: "15px",
    padding: "14px",
    minWidth: "132px",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "space-between",
  },
  tableContent: {
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "space-between",
    padding: "0 1rem 0.75rem 1rem",
  },
  seatContent: {
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "flex-end",
    gap: "0.25rem",
  },
  tableDetailsIcon: {
    display: "flex",
    width: "fit-content",
    flexDirection: "column" as "column",
    backgroundColor: "#A6CCC0",
    borderRadius: "8px",
    padding: "0.65rem",
    marginLeft: "auto",
  },
  tableText: {
    fontSize: "14px",
    fontWeight: "400",
  },
  tableTextNew: {
    fontSize: "16px",
    fontWeight: "400",
  },
  seatsTextNew: {
    fontSize: "12px",
    fontWeight: "400",
  },
  tableNo: {
    fontSize: "32px",
    fontWeight: "500",
    lineHeight: "1",
  },
  tableNoNew: {
    fontSize: "34px",
    fontWeight: "400",
    lineHeight: "1",
  },
  seatsNoNew: {
    fontSize: "26px",
    fontWeight: "400",
    lineHeight: "1",
  },
  tableManagementHeader: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    padding: "0 1rem 1rem 0rem",
    marginTop: -15,
    marginBottom: -15,
  },
  tabelButton: {
    fontWeight: "bold",
    // marginBottom: "22px",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "center",
    gap: "0.5rem",
    alignItems: "center",
    cursor: "pointer",
  },
  addTableUpperSection: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    gap: "2rem",
  },
  addTableUpperSectionSecondary: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "2rem",
  },
  addTableBottomSection: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
  },
  addTableStatus: {
    display: "flex",
    flexDirection: "column" as "column",
    fontSize: 11,
  },
  addTableName: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "16px",
    backgroundColor: "#1B1B1B",
    padding: "1rem",
    color: "#FFF",
    width: "9.5rem",
  },
  updateLabelF: {
    fontSize: "0.75rem",
    fontWeight: "400",
  },
  updateLabel: {
    fontSize: "0.875rem",
    fontWeight: "700",
  },
  generateQr: {
    borderRadius: "10px",
    // padding: "14px",
    minWidth: "132px",
    aspectRatio: "1 / 1",
    display: "flex",
    flexDirection: "column" as "column",
    // gap: "1rem",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid",
  },
  qr: {
    minWidth: "132px",
    borderRadius: "10px",
    aspectRatio: "1 / 1",
    border: "1px solid",
  },
  modal: {
    height: "35rem",
  },
  tableManagementHeaderLeft: {
    display: "flex",
    flexDirection: "row" as "row",

    padding: "0 1rem",
  },
  tableHeaderInfo: {
    display: "flex",
    flexDirection: "column" as "column",
    padding: "0 0.5rem",
  },
  tableHeaderInfoContent: {
    display: "flex",
    flexDirection: "row" as "row",
    alignItems: "center",
    gap: "0.5rem",
  },
  tableHeaderInforCircle: {
    width: "0.438rem",
    height: "0.438rem",
    borderRadius: "50%",
  },
  layoutChangeBtn: {
    display: "flex",
    alignItems: "center",
    borderRadius: "15px",
    width: "fit-content",
    padding: "0.2rem 0.5rem",
    height: "85%",
  },
  layoutOption: {
    // border:"1px solid",
    padding: "0.5rem",
    borderRadius: "15px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    maxHeight: "85%",
    width: "3.2rem",
    cursor: "pointer",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  newTableModal: {
    top: 140,
    right: "-30%",
  },
  leftHeader: {
    width: "1px",
    height: "100%",
  },
  /////////Settings icon //////////////
  settingsContainer: {
    marginTop: "150px",
    marginLeft: "-135px",
    gap: "1rem",
    padding: "0.6rem",
    width: "max-content",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "center" as "center",
    borderRadius: "15px",
    position: "absolute" as "absolute",
    zIndex: "100",
    fontSize: 12,
    fontWeight: 600,
  },
  settingIconsContainer: {
    display: "flex",
    alignItems: "center",
    padding: "0px 10px 0 10px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
  },
  settingIcons: {
    marginRight: 6,
    fontSize: "12px",
  },
  settingTexts: {
    margin: 0,
    marginTop: "auto",
    marginBottom: "auto",
    fontSize: "14px",
    fontWeight: 500,
  },
  editItems: {
    display: "flex",
    alignItems: "center",
    padding: "4px 10px 4px 10px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
  },
};

export default style;
