const style = {
  container: {
    borderRadius: "15px",
    background: "#FFF",
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
    padding: "12px 9px",
  },
  orderItemHeader: {
    display: "flex",
    flexDirection: "row" as "row",
    gap: "1rem",
    alignItems: "center",
  },
  detailModal: { top: 20, right: "-25%", minHeight: "570px" },
  modelTitle: { fontSize: "20px", marginBottom: 0, paddingBottom: 0 },

  orderItemCard: {
    padding: "1rem 1rem 5rem 1rem",
  },

  orderItemNo: {
    fontSize: "1.125rem",
    minWidth: "3.938rem",
    height: "3.938rem",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "400",
    borderRadius: "15px",
  },
  arrowIcon: {
    position: "absolute",
    right: 0,
    fontSize: "20px",
    marginRight: 5,
  },
  orderItemName: {
    color: "#000",
    fontSize: "16px",
    fontWeight: "700",
  },
  orderNo: {
    color: "#464646",
    fontSize: "12px",
    fontWeight: "400",
    flex: "none",
  },
  orderStatus: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "5.5rem",
    height: "1.5rem",
    borderRadius: "10px",
    backgroundColor: "#FAD194",
    fontSize: "12px",
    fontWeight: "400",
  },
  orderDate: {
    fontSize: "14px",
    fontWeight: "400",
  },
  hrLine: {
    height: "1px",
    width: "100%",
    backgroundColor: "rgba(215, 215, 215, 1)",
  },
  orderTable: {
    height: "100%",
    width: "100%",
    borderSpacing: "10px",
  },
  orderTableHeadingsRow: {
    color: "#737373",
    fontSize: "12px",
    fontWeight: "400",
    marginTop: "0.5rem",
    marginBottom: "0.5rem",
  },
  orderTableRow: {
    color: "#1A1A1A",
    fontSize: "12px",
    fontWeight: "400",
    marginTop: "0.5rem",
    marginBottom: "0.5rem",
  },
  orderTableHeading: {
    textlign: "start",
    fontWeight: "400",
  },
  orderBottomSection: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
  },
  orderItemBody: {
    display: "flex",
    flexDirection: "row" as "row",
    gap: "1rem",
  },
  orderTotalText: {
    fontSize: "12px",
    fontWeight: "700",
  },
  orderSeeDetailsBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    background: "#E4EFFF",
    outline: "none",
    color: "#2F2F2F",
    fontSize: "12px",
    fontWeight: "400",
    width: "6.125rem",
  },
  orderPayBillsBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    background: "#000",
    color: "#FFF",
    fontSize: "12px",
    fontWeight: "700",
  },
};
export default style;
