const style = {
  searchIcon: {
    color: "#000000",
    width: "16.19px",
    height: "18px",
    fontSize: "20px",
    cursor: "pointer",
  },
  searchBar: {
    width: "217px",
    height: 30,
    marginRight: "auto",
    marginLeft: "auto",
    borderRadius: "10px",
  },
  inputContainer: {
    // position: "relative" as "relative",
    width: "226px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  menuHeaderLeftStatus: {
    marginTop: 10,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "402px",
    height: "40px",
    // padding: "0.5rem 1rem",
    borderRadius: "15px",
    // marginLeft: "auto",
  },
  menuHeaderMiddleBtn: {
    marginTop: 10,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    height: 50,
    borderRadius: "15px",
  },
  menuHeaderRight: {
    marginTop: 10,
    display: "flex",
    alignItems: "center",
    width: "226px",
    height: 40,
    padding: "0.5rem",
    borderRadius: "15px",
    // marginLeft: "auto",
  },
  menuHeaderInfo: {
    display: "flex",
    flexDirection: "row" as "row",
    padding: "0 2rem",
  },
  menuHeaderLeft: {
    borderRadius: "12px",
    padding: "8px 14px",
    textAlign: "center" as "center",
    cursor: "pointer",
    position: "relative" as "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 600,
  },
  headerItems: {
    position: "absolute" as "absolute",
    top: -4,
    right: -4,
    borderRadius: "50%",
    width: "16px",
    height: "16px",
    display: "flex",
    alignItems: "center" as "center",
    justifyContent: "center" as "center",
  },
  headerItemsText: {
    fontWeight: 500,
    fontSize: 11,
  },
  tableText: {
    fontSize: 20,
  },
  tableTextCollapse: {
    marginLeft: 5,
    marginTop: 0,
    marginBottom: 0,
  },
  tableContainer: {
    display: "flex",
    flexDirection: "row" as "row",
    alignItems: "center" as "center",
    justifyContent: "center" as "center",
    borderRadius: "12px",
    fontWeight: 600,
    cursor: "pointer",
    minWidth: "130px",
    height: "36px",
    fontSize: "14px",
  },
  settingsContainer: {
    display: "flex",
    flexDirection: "row" as "row",
    alignItems: "center" as "center",
    padding: "6px 12px",
    borderRadius: "12px",
    fontWeight: 500,
    cursor: "pointer",
  },
  iconView: {
    fontSize: "20px",
  },
  menuHeaderMiddle: {
    padding: "8px",
    borderRadius: "12px",
    fontWeight: 500,
    cursor: "pointer",
  },
  headerleftText: {
    margin: 0,
    padding: 0,
  },
  headerleftTextView: {
    margin: 0,
    marginLeft: 17,
    padding: 0,
  },
  menuHeaderMiddleView: {
    marginLeft: 10,
    marginRightt: 10,
    padding: 0,
  },
};
export default style;
