import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  card: {
    backgroundColor: "#fff",
    overflow: "hidden",
    fontSize: "18px",
    color: "#fff",
    fontFamily: "'Material Design Icons'",
  },
  cardInner: {
    position: "absolute",
    width: "219px",
    height: "215px",
  },
  absoluteDiv: {
    position: "absolute",
    height: "100%",
    width: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: "10px",
    backgroundColor: "#2f3135",
  },
  settingsIcon: {
    position: "absolute",
    top: "83.72%",
    left: "6.85%",
    fontSize: "22px",
    color: "#ededed",
  },
  imageDiv: {
    position: "absolute",
    top: "-10px",
    left: "-10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "10px",
  },
  image: {
    position: "relative",
    borderRadius: "10px 10px 0px 0px",
    width: "219px",
    height: "79px",
    objectFit: "cover",
  },
  title: {
    position: "absolute",
    top: "40.47%",
    left: "5.02%",
    fontWeight: "600",
    fontFamily: "Inter",
  },
  price: {
    position: "absolute",
    top: "53.49%",
    left: "5.02%",
    fontSize: "16px",
    fontFamily: "Inter",
  },
  counterDiv: {
    position: "absolute",
    height: "11.16%",
    width: "40.18%",
    top: "85.12%",
    right: "4.57%",
    bottom: "3.72%",
    left: "55.25%",
  },
  plusButton: {
    position: "absolute",
    height: "100%",
    width: "27.27%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "72.73%",
  },
  plusButtonInner: {
    position: "absolute",
    height: "100%",
    width: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: "10px",
    border: "1px solid #fff",
    boxSizing: "border-box",
  },
  minusButton: {
    position: "absolute",
    height: "100%",
    width: "27.27%",
    top: "0%",
    right: "72.73%",
    bottom: "0%",
    left: "0%",
  },
  minusButtonInner: {
    position: "absolute",
    height: "100%",
    width: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: "10px",
    border: "1px solid #fff",
    boxSizing: "border-box",
  },
  counter: {
    position: "absolute",
    top: "4.17%",
    left: "44.32%",
    fontWeight: "300",
    fontFamily: "Inter",
  },
  ingredients: {
    position: "absolute",
    height: "11.16%",
    width: "86.76%",
    top: "64.65%",
    left: "5.94%",
    fontSize: "12px",
    fontFamily: "Inter",
    color: "#7c7c7c",
    display: "inline-block",
  },
  whiteBox: {
    position: "absolute",
    height: "8.84%",
    width: "16.44%",
    top: "5.58%",
    right: "2.74%",
    bottom: "85.58%",
    left: "80.82%",
    borderRadius: "10px",
    backgroundColor: "#fff",
  },
  dotsIcon: {
    position: "absolute",
    top: "6.05%",
    left: "84.93%",
    color: "#000",
  },
};
