const style = {
  menuItemContainer: {
    borderRadius: "10px",
    // padding: "14px",
    aspectRatio: "1 / 1",
    justifyContent: "space-between",
    cursor: "pointer",
  },
  menuItem: {
    justifyContent: "space-between",
  },
  colourPickerBox: {
    minWidth: "41px",
    maxWidth: "41px",
    height: "41px",
    borderRadius: "10px",
  },
  updateLabelF: {
    fontSize: "0.75rem",
    fontWeight: "400",
  },
  updateLabel: {
    fontSize: "0.875rem",
    fontWeight: "700",
  },
  generateQr: {
    borderRadius: "10px",
    padding: "14px",
    minWidth: "132px",
    aspectRatio: "1 / 1",
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid",
  },
  titleTxt: {
    fontSize: "1.125rem",
    fontWeight: "700",
  },
  subTxt: {
    fontSize: "0.875rem",
    fontWeight: "400",
  },
  cardContainer: {
    padding: "0.25rem",
    borderRadius: "15px",
    borderTop: 0,
    borderRight: "3px solid transparent",
    borderLeft: "3px solid transparent",
    margin: "0 -5px 0 -5px",
  },
  bodyStyle: {
    marginBottom: "0.5rem",
    marginTop: -6,
    paddingBottom: "0",
  },
  card: {
    borderRadius: "10px",
    width: "230px",
    height: "150px",
    // minWidth: "200px",
    // maxWidth: "200px",
    // minHeight: "171px",
    // maxHeight: "171px",
    cursor: "pointer",
    position: "relative" as "relative",
  },
  cardOptions: {
    position: "absolute" as "absolute",
    top: "12px",
    right: "21px",
    cursor: "pointer",
    // cursor: "not-allowed",
  },
  cardIcon: {
    padding: "0",
    fontSize: "32px",
    fontWeight: 400,
  },
  cardTitle: {
    fontSize: "18px",
    fontWeight: 700,
    lineHeight: "21.93px",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical" as "vertical",
    WebkitLineClamp: 2,
    overflow: "hidden",
    marginTop: -5,

    // paddingBottom: "0.2rem",
  },
  cardText: {
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: "0.875rem",
    paddingTop: "0.2rem",
  },
  itemContainer: {
    borderTopLeftRadius: "10px",
  },
  itemBodyStyle: {
    width: "280px",
    minHeight: 160,
    margin: 0,
    padding: 0,
  },
  itemCard: {
    width: "280px",
    height: "340px",
  },
  itemOptions: {
    position: "absolute" as "absolute",
    top: "16px",
    right: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    width: 34,
    height: 16,
    borderRadius: "10px",
  },
  fireIcon: {
    position: "absolute" as "absolute",
    top: -104,
    left: 12,
    width: 35,
    height: 35,
  },
  itemTitleContainer: {
    margin: "16px 0.8rem",
  },
  itemTitle: {
    fontWeight: 600,
    margin: 0,
    lineHeight: "22px",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical" as "vertical",
    WebkitLineClamp: 2,
    overflow: "hidden",
  },

  priceStyle: {
    padding: 0,
    margin: "3px 0",
    fontSize: "16px",
    fontWeight: 400,
  },
  itemDescription: {
    fontSize: "14px",
    fontWeight: 400,
    margin: 0,
    lineHeight: "1.2rem",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical" as "vertical",
    WebkitLineClamp: 3,
    overflow: "hidden",
    height: "55px",
  },
  itemLabelContainer: {
    margin: "15px 0 15px 0",
  },
  itemLable: {
    padding: "0.25rem 0.7rem",
    borderRadius: 15,
    fontSize: "12px",
    fontWeight: 400,
  },
};

export default style;
