const style = {
  tableContainer: {
    padding: "1rem",
  },
  container: {
    borderRadius: "10px",
    padding: "14px",
    minWidth: "132px",
    aspectRatio: "1 / 1",
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "space-between",
    cursor: "pointer",
  },
  tableContent: {
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "space-between",
  },
  menuBtn: {
    borderRadius: 10,
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    fontWeight: 600,
  },
  tableDetailsIcon: {
    display: "flex",
    flexDirection: "column" as "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#A6CCC0",
    borderRadius: "8px",
    padding: "0.65rem",
  },
  tableText: {
    fontSize: "14px",
    fontWeight: "400",
  },
  tableNo: {
    fontSize: "32px",
    fontWeight: "600",
    lineHeight: "1",
  },
  menuManagementHeader: {
    padding: "5px 1rem 6px 1rem",
    marginBottom: 0,
  },
  tabelButton: {
    padding: "0.5rem",
    fontWeight: "bold",
    fontSize: "16px",
    marginBottom: "22px",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "center",
    gap: "0.5rem",
    alignItems: "center",
    cursor: "pointer",
  },
  addTableContainer: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "2rem",
  },
  addTableUpperSection: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    gap: "2rem",
  },
  addTableUpperSectionSecondary: {
    display: "flex",
    flexDirection: "column" as "column",
    gap: "2rem",
  },
  addTableBottomSection: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
  },
  addTableStatus: {
    display: "flex",
    flexDirection: "column" as "column",
    fontSize: "14px",
  },
  addTableName: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "16px",
    backgroundColor: "#1B1B1B",
    padding: "1rem",
    color: "#FFF",
    width: "9.5rem",
  },
  generateQr: {
    borderRadius: "10px",
    padding: "14px",
    minWidth: "132px",
    aspectRatio: "1 / 1",
    display: "flex",
    flexDirection: "column" as "column",
    gap: "1rem",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid",
  },
  qr: {
    minWidth: "132px",
    borderRadius: "10px",
    aspectRatio: "1 / 1",
    border: "1px solid",
  },
  modal: {
    height: "33rem",
  },
  menuManagementHeaderLeft: {
    gap: "2rem",
    padding: "0 1rem",
  },
  menuHeaderInfo: {
    display: "flex",
    flexDirection: "column" as "column",
  },

  searchHeaderInfo: {
    display: "flex",
    width: "fit-content",
    alignItems: "center",
    padding: "0",
    marginLeft: "auto",
  },

  menuHeaderInfoLeft: {
    display: "flex",
    flexDirection: "column" as "column",
    padding: "0 2rem",
    // borderLeft: "1px solid",
    backgroundColor: "#ffffff",
  },
  menuHeaderInfoContent: {
    display: "flex",
    flexDirection: "row" as "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1.5rem",
  },
  menuHeaderInfoContentDown: {
    display: "flex",
    flexDirection: "row" as "row",
    // justifyContent: "space-between",
    alignItems: "center",

    marginTop: 8,
  },
  menuHeaderInforCircle: {
    width: "0.438rem",
    height: "0.438rem",
    borderRadius: "50%",
  },
  verticalLine: {
    minHeight: "8vh",
    display: "flex",
    justifyContent: "center" as "center",
  },
  rowSpaceBetween: {
    // display: "flex",
    // justifyContent: "space-between",
  },
  menuHeaderRight: {
    position: "relative" as "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: 50,
    borderRadius: "15px",
    marginTop: 5,
  },

  settingIcon: {
    display: "flex",
    justifyContent: "center" as "center",
    alignItems: "center",
    fontSize: 20,
    cursor: "pointer",
    width: 44,
    height: 33,
    borderRadius: "10px",
    marginLeft: 10,
  },
  menuHeaderLeftContent: {
    justifyContent: "left" as "left",
    backgroundColor: "#000000",
    padding: "1rem",
    display: "flex",
    alignItems: "flex-start",
  },
  searchBar: {
    height: 40,
    width: 380,
    margin: "0 6px",
    borderRadius: "10px",
  },
  inputIcons: {
    position: "absolute" as "absolute",
    fontSize: "20px",
    cursor: "pointer",
    top: "35%",
    right: "5%",
    transform: "translateY(-50%)",
  },
  inputField: {
    fontSize: "14px",
    height: "30px",
    width: "100%",
    border: "transparent",
    marginBottom: "22px",
  },
  inputContainer: {
    position: "relative" as "relative",
  },
  menuText: {
    fontSize: "12px",
    fontWeight: "400",
  },
  menuIcon: {
    fontSize: "2.5rem",
  },
  menuTextSpan: {
    fontWeight: "700",
  },
  searchIcon: {
    position: "absolute" as "absolute",
    fontSize: "20px",
    cursor: "pointer",
    top: "48%",
    right: "7%",
    transform: "translateY(-50%)",
    color: "#000000",
  },

  settingIcons: {
    marginRight: 6,
    fontSize: "1rem",
    marginTop: "0.7rem",
  },
  settingTexts: {
    margin: 0,
    marginTop: "0.7rem",
    marginBottom: "auto",
  },
};

export default style;
