import { CSSProperties } from "react";
export const styles: { [key: string]: CSSProperties } = {
  feedStyle: {
    borderRadius: "20px",
    backgroundColor: "#2f3135",
    width: "246px",
    height: "197px",
    margin: "0px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "9px 8px 14px 10px",
    gap: "22px",
    textAlign: "left",
    fontSize: "16px",
    color: "#fff",
    marginTop: "10px",
  },
  innerDivStyle: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    textAlign: "left",
    fontSize: "18px",
    color: "#fff",
    margin: "0px",
  },
  notificationStyle: {
    position: "relative",
    width: "24px",
    height: "24px",
    fontSize: "12px",
    fontFamily: "Inter",
    margin: "0px",
  },
  notificationNumberStyle: {
    position: "absolute",
    top: "0px",
    left: "0px",
    borderRadius: "50%",
    backgroundColor: "#b02133",
    width: "24px",
    height: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    zIndex: "1",
    margin: "2px 0px 0px -20px",
  },
  feedbackStyle: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: "10px",
    textAlign: "left",
    fontSize: "18px",
    color: "#fff",
    margin: "0px",
  },
  feedbackTitleStyle: {
    margin: "0",
    position: "relative",
    fontSize: "inherit",
    fontWeight: "400",
    fontFamily: "inherit",
    zIndex: "1",
  },
  feedbackContentStyle: {
    flex: "1",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: "7px",
    fontSize: "12px",
    fontFamily: "Inter",
    margin: "0px",
  },
  feedbackTextStyle: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "0px 0px 0px 3px",
    margin: "0px",
  },
  starRatingStyle: {
    position: "relative",
    fontFamily: "'Material Design Icons'",
    color: "#68ffb7",
    paddingRight: "20px",
    zIndex: "1",
  },
  viewAllStyle: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "flex-start",
    gap: "0px",
    fontSize: "12px",
    fontFamily: "Inter",
    color: "#000",
  },
  borderStyle: {
    alignSelf: "stretch",
    position: "relative",
    borderTop: "1px solid rgba(137, 137, 137, 0.3)",
    boxSizing: "border-box",
    height: "0px",
    zIndex: "1",
    margin: "-10px 0px 0px 0px",
  },
  viewAllContentStyle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "0px 27px",
    margin: "7px 0px 0px 0px",
  },
  viewAllTextStyle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    margin: "0px",
    gap: "10px",
  },
  viewAllIconStyle: {
    position: "relative",
    fontFamily: "'Material Design Icons'",
    color: "#3b7ff2",
    margin: "2px 0px 0px 0px",
    zIndex: "1",
  },
};
