import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  divStyle: {
    position: "relative",
    width: "100%",
    overflow: "hidden",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionStyle: {
    borderRadius: "16px",
    height: "110px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "3px 0px 7px 1px",
    boxSizing: "border-box",
    gap: "3px",
    textAlign: "left",
    fontSize: "9px",
    fontFamily: "'Material Design Icons'",
  },
  hiddenDiv: {
    position: "relative",
    borderRadius: "16px",
    width: "48px",
    height: "110px",
    display: "none",
  },
  iconDiv: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "0px 16px 0px 5px",
    fontSize: "28px",
  },
  icon: {
    margin: "0",
    position: "relative",
    //fontSize: "inherit",
    fontSize: "28px",
    fontWeight: "400",
    fontFamily: "inherit",
    display: "inline-block",
    height: "27px",
    zIndex: "1",
  },
  flexRow: {
    flex: "1",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "0px 14px 0px 11px",
    textAlign: "center",
    fontSize: "10px",
    fontFamily: "Inter",
  },
  stretchDiv: {
    alignSelf: "stretch",
    position: "relative",
    zIndex: "1",
  },
  margin0: {
    margin: "0",
    height: "17px",
  },
  fontSize15: {
    margin: "0",
    fontSize: "15px",
  },
  relativeDiv: {
    position: "relative",
    borderTop: "1px solid #4a5fbc",
    boxSizing: "border-box",
    width: "48px",
    height: "1px",
    zIndex: "2",
  },
  paddingDiv: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "0px 22px 0px 18px",
  },
  relativeZ1: {
    position: "relative",
    zIndex: "1",
  },
  relativeZ2: {
    position: "relative",
    zIndex: "2",
    fontFamily: "Inter",
  },
  fontSize8: {
    fontSize: "8px",
  },
};
