import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  feedStyle: {
    position: "relative",
    backgroundColor: "#17181a",
    width: "170px",
    height: "130px",
    overflow: "hidden",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "25px 10px 33px 18px",
    boxSizing: "border-box",
    gap: "14px",
    textAlign: "left",
    fontSize: "28px",
    color: "#fff",
    fontFamily: "'Material Design Icons'",
  },
  divStyle1: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "3px 0px 0px",
    margin: "10px 0px 0px 0px",
  },
  titleStyle: {
    margin: "0",
    position: "relative",
    fontSize: "inherit",
    fontWeight: "400",
    fontFamily: "inherit",
  },
  divStyle2: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    fontSize: "14px",
    color: "#e4e4e4",
    fontFamily: "Inter",
  },
  divStyle3: {
    position: "relative",
    fontWeight: "300",
    display: "inline-block",
    height: "40px",
    flexShrink: "0",
  },
  paragraphStyle1: {
    // fontWeight: 'bold',
    margin: "",
  },
  paragraphStyle2: {
    margin: "-17px 0px 0px 0px",
  },
  divStyle4: {
    position: "relative",
    fontSize: "24px",
    fontWeight: "300",
    display: "inline-block",
    width: "68px",
    height: "22px",
    flexShrink: "0",
    paddingRight: "20px",
    margin: "-10px 0px 0px -3px",
  },
};
