/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import { CognitoUserPool } from "amazon-cognito-identity-js";

export const AwsExport = {
  aws_project_region: process.env.NEXT_PUBLIC_COGNITO_REGION,
  aws_project_region: process.env.NEXT_PUBLIC_COGNITO_REGION,
  aws_cognito_identity_pool_id:
    process.env.NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: process.env.NEXT_PUBLIC_COGNITO_REGION,
  aws_user_pools_id: process.env.NEXT_PUBLIC_COGNITO_POOL_ID,
  aws_user_pools_web_client_id:
    process.env.NEXT_PUBLIC_USER_POOLS_WEB_CLIENT_ID,
};

const poolData = {
  UserPoolId: process.env.NEXT_PUBLIC_COGNITO_POOL_ID,
  ClientId: process.env.NEXT_PUBLIC_USER_POOLS_WEB_CLIENT_ID,
};

export const userPool = new CognitoUserPool(poolData);
